export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const ADD_SNACKBAR = 'ADD_SNACKBAR'
export const ADD_INFO_SNACKBAR = 'ADD_INFO_SNACKBAR'
export const ADD_WARNING_SNACKBAR = 'ADD_WARNING_SNACKBAR'
export const ADD_ERROR_SNACKBAR = 'ADD_ERROR_SNACKBAR'
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR'

export const SEARCH_MOVIE_STARTED = 'SEARCH_MOVIE_STARTED'
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS'
export const SEARCH_MOVIE_FAILED = 'SEARCH_MOVIE_FAILED'
export const SEARCH_MOVIE_RESET = 'SEARCH_MOVIE_RESET'

export const LOAD_PROFILE_STARTED = 'LOAD_PROFILE_STARTED'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAILED = 'LOAD_PROFILE_FAILED'